name: Build iOS macOS 15

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Check environment
      run: |
        echo "=== Xcode ==="
        xcodebuild -version
        echo "=== .NET ==="
        dotnet --version
        
    - name: Install MAUI
      run: dotnet workload install maui-ios
      
    - name: Build iOS Simulator
      run: dotnet build SRQCC.csproj -c Release -f net9.0-ios -p:Platform=iPhoneSimulator
        
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: "**/bin/Release/net9.0-ios/**/*.app"