name: Build MAUI iOS Simple

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install MAUI
      run: dotnet workload install maui-ios
      
    - name: Build iOS App
      run: |
        dotnet build SRQCC.csproj \
          -c Release \
          -f net9.0-ios \
          -p:Platform=iPhoneSimulator \
          -p:BuildIpa=false
        
    - name: Upload App Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: "**/bin/Release/net9.0-ios/**/*.app"