name: Build iOS .NET 8

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install MAUI
      run: dotnet workload install maui-ios
      
    - name: Build iOS
      run: dotnet build -c Release -f net8.0-ios -p:Platform=iPhoneSimulator
        
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: "**/bin/Release/net8.0-ios/**/*.app"