name: Build iOS Force

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install MAUI ignoring warnings
      run: |
        dotnet workload install maui-ios --ignore-failed-sources
        dotnet workload restore --ignore-failed-sources
      
    - name: Build with specific SDK
      run: |
        dotnet build SRQCC.csproj \
          -c Release \
          -f net9.0-ios \
          -p:Platform=iPhoneSimulator \
          -p:BuildIpa=false \
          -p:MicrosoftNETCoreAppVersion=9.0.0 \
          --no-restore