name: Build MAUI iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install MAUI workloads
      run: |
        dotnet workload install maui
        dotnet workload install maui-ios
        dotnet workload restore
      
    - name: Restore dependencias NuGet
      run: dotnet restore
      
    - name: Verificar estructura del proyecto
      run: |
        ls -la
        ls -la Platforms/iOS/ || echo "No existe Platforms/iOS/"
        find . -name "*.csproj" -type f
      
    - name: Build para Simulador (.app)
      run: |
        dotnet build -c Release -f net9.0-ios \
        -p:Platform=iPhoneSimulator \
        -p:BuildIpa=false \
        --verbosity detailed
      
    - name: Build para Dispositivo (.ipa)
      run: |
        dotnet build -c Release -f net9.0-ios \
        -p:Platform=iPhone \
        -p:BuildIpa=true \
        --verbosity detailed
        
    - name: Listar archivos generados
      run: |
        echo "=== Buscando archivos .app ==="
        find . -name "*.app" -type d 2>/dev/null || echo "No se encontraron .app"
        echo "=== Buscando archivos .ipa ==="
        find . -name "*.ipa" -type f 2>/dev/null || echo "No se encontraron .ipa"
        echo "=== Contenido de bin/ ==="
        ls -la */bin/Release/net9.0-ios*/ 2>/dev/null || echo "No hay binarios generados"
        
    - name: Subir artefactos (.ipa)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa-file
        path: |
          **/bin/Release/net9.0-ios/iphone/*.ipa
        retention-days: 30
        
    - name: Subir artefactos (.app)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-simulator
        path: |
          **/bin/Release/net9.0-ios/iphonesimulator/*.app
        retention-days: 30